### ISSUE TITLE
Write messages

### ISSUE THREAD

**Issue by giena** [krasserm/akka-persistence-kafka#24]
The asyncWriteMessages is like this: 
def asyncWriteMessages(messages: Seq[PersistentRepr]): Future[Unit] = {
    val sends = messages.groupBy(_.persistenceId).map {
      case (pid, msgs) => writerFor(pid).ask(messages)(writeTimeout)
    }
    Future.sequence(sends).map(_ => ())
  }

I think it should be like this:
def asyncWriteMessages(messages: Seq[PersistentRepr]): Future[Unit] = {
    val sends = messages.groupBy(_.persistenceId).map {
      case (pid, msgs) => writerFor(pid).ask(msgs)(writeTimeout)
    }
    Future.sequence(sends).map(_ => ())
  }

Do i make a mistake?

**Comment by krasserm** [comment]
Ouch, that's really a bug, good catch. It just didn't surface because a message batch sent by akka-persistence only contains messages with the same `persistenceId`. Do you want to create a pull request? Maybe along with a test that demonstrates that the bug is fixed?

**Comment by giena** [comment]
I've created a pull request: https://github.com/krasserm/akka-persistence-kafka/pull/25
But no test.
