### ISSUE TITLE
Does the max number of persistenceId has limits, when one to one mapping from persistentId to kafka topic?

### ISSUE THREAD

**Issue by MQ-EL** [krasserm/akka-persistence-kafka#29]
Hi @krasserm 

  I am trying to learn&modify your persistence-kafka for support akka 2.4.0, but has some of the problems encountered:

```
1. The nr of persistenceId has upper limit? due to the limit of kafka topics

2. When i have several millions of persistent actors, the cassandra could be a better choice?
```

**Comment by krasserm** [comment]
@MQ-EL yes, that's a known limitation. Not only for a large number of persistent actors, the Cassandra plugin is a better choice ;)

**Comment by MQ-EL** [comment]
Thank you very much. :)

**Comment by krasserm** [comment]
Close the ticket?

**Comment by MQ-EL** [comment]
Excute me, I still has some question need to consult (akka persistent module):
1. 

``` scala
  class Resequencer extends Actor {
    import scala.collection.mutable.Map

    private val delayed = Map.empty[Long, Desequenced]
    private var delivered = 0L

    def receive = {
      case d: Desequenced ⇒ resequence(d)
    }

    @scala.annotation.tailrec
    private def resequence(d: Desequenced) {
      if (d.snr == delivered + 1) {
        delivered = d.snr
        d.target.tell(d.msg, d.sender)
      } else {
        delayed += (d.snr -> d)
      }
      val ro = delayed.remove(delivered + 1)
      if (ro.isDefined) resequence(ro.get)
    }
  }
```

we can require mailbox type limit to FIFO sematic, because the AsyncJournalWriter and this Resequencer live in the same actor system, so disordering never happened, does it right?

2.
  Did cassandra proven to support serveral millions of persistent actor in production? I haven't experience for it in production :(

**Comment by krasserm** [comment]
> we can require mailbox type limit to FIFO sematic, because the AsyncJournalWriter and this Resequencer live in the same actor system, so disordering never happened, does it right?

This re-ordering is needed because write completion notifications from a storage backend may have different order than write requests. It's not related to journal-resequencer communication.

> Did cassandra proven to support serveral millions of persistent actor in production? I haven't experience for it in production :(

There are several people/companies using it in production and I didn't hear about problems for scaling with the number of persistent actors.

**Comment by MQ-EL** [comment]
TYVM
