### ISSUE TITLE
Add support for new Kafka Producer

### ISSUE THREAD

**Issue by eugenemiretsky** [krasserm/akka-persistence-kafka#31]
It would be nice to upgrade to the new Java Kafka producer (0.8.2+ ).
Since it is Async, you probably don't need the worker pool. 

I can create a pull request if you're ok with the change. 

p.s
How come you decided to use the Sync Kafka producer in instead of the async?

**Comment by krasserm** [comment]
> How come you decided to use the Sync Kafka producer in instead of the async? 

That's explained in #20. If you still see an option how to deal with the problems described there, I'd be more than happy to review your PR. If you want to work on it please refer to #20, I'll close this ticket because it's a duplicate.
