### ISSUE TITLE
Is this project dead ? 

### ISSUE THREAD

**Issue by idanna** [krasserm/akka-persistence-kafka#35]

**Comment by krasserm** [comment]
I don't have any plans at the moment to continue working on it.

**Comment by ktoso** [comment]
I would add that rather than as a persistence plugin, we've seen Kafka usage in the Akka ecosystem evolve into the direction of using APIs as Akka Streams, so via https://github.com/akka/reactive-kafka which is actively maintained

**Comment by krasserm** [comment]
... and one of many application examples is https://github.com/krasserm/akka-stream-eventsourcing. It is a stream-based alternative to akka-persistence (still alpha though).
